### ISSUE TITLE
Question: Does it work with Shopware 6

### ISSUE THREAD

**Issue by amenk** [tinect/TinectMatomo#5]
Does the plugin work with Shopware 6? Let's state that in the readme :)

**Comment by amenk** [comment]
@tinect thanks

**Comment by tinect** [comment]
Hey @amenk 
Maybe you can try this: https://github.com/Jinya-CMS/matomo-shopware-plugin

But I've not tested yet.

**Comment by amenk** [comment]
@tinect yes, also saw that. Already made a PR :D But it's a very fresh one.
